### ISSUE TITLE
Ramses all-app Draft

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Ramses#86]
To be moved from issues to the doc.  
Re-work all the doc in md, and publish.

This is a reference for all implementations of Ramses, these guidelines and definitions should be followed for every tool working with Ramses.

# General

## Paths

Paths may start with a placeholder for the Project folder "%ProjectShortName%" or the Ramses folder "%Ramses%". In other cases the path is absolute.

**Comment by Pravahati** [comment]
Typos:
- Ramses, Attributes, online: "when client app is available and respondona" -> responding
- Ramses, Attributes, folderPath: "the absolute path" -> The
- RamState: "like CHK (To bbe checked)" -> to be
- RamState: missing "Attributes" before the list of attributes
- Everywhere: replace "boolean" with "bool" and "string" with "str"?

**Comment by Pravahati** [comment]
RamStatus: add attribute 'published', bool

**Comment by Pravahati** [comment]
# RamItem, inherits RamObject

- published

static methods

- getFromPath

Methods:

- getLatestVersion
- getLatestPubVersion
